# Generated by Django 4.0.5 on 2022-08-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cart_final_price_cart_and_more'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products_in_order',
            field=models.ManyToManyField(related_name='products_in_order', to='cart.cartproduct', verbose_name='Заказаные товары'),
        ),
    ]
