# Generated by Django 4.0.5 on 2022-08-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_product_favorite_products_favoriteuserproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=255, verbose_name='Название акции')),
                ('image_stock', models.ImageField(blank=True, default='product/system_img/default.jpg', upload_to='stock/%Y/%m/%d/', verbose_name='Банер акции')),
                ('products_in_stock', models.ManyToManyField(related_name='products_in_stock', to='product.product', verbose_name='Продукты в акции')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
            },
        ),
    ]
