# Generated by Django 4.0.5 on 2022-08-06 12:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_product_favorite_products_favoriteuserproduct'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_products', models.IntegerField(default=0, verbose_name='Количество товара')),
                ('final_price_cart', models.IntegerField(default=0, verbose_name='Общая сумма всех товаров')),
                ('total_discount_price', models.IntegerField(default=0, verbose_name='Общая сумма скидок')),
                ('total_not_discount_price', models.IntegerField(default=0, verbose_name='Общая сумма цен без скидок')),
                ('in_order', models.BooleanField(default=False, verbose_name='В заказе')),
                ('for_anonymous_user', models.BooleanField(default=False, verbose_name='Анонимный пользователь')),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Cart',
            },
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_product', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2147483647)], verbose_name='Количество')),
                ('final_price', models.IntegerField(default=0, verbose_name='Общая сумма')),
                ('final_total_discount', models.IntegerField(default=0, verbose_name='Общая сумма скидок в корзине')),
                ('final_price_not_discount', models.IntegerField(default=0, verbose_name='Общая сумма цен без скидок в корзине')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_products', to='cart.cart', verbose_name='Корзина')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Product in cart',
                'verbose_name_plural': 'Products in cart',
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='products_in_cart',
            field=models.ManyToManyField(blank=True, related_name='products_in_cart', to='cart.cartproduct'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_in_cart_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
