# Generated by Django 4.0.5 on 2022-08-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cartproduct_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='final_price_cart',
            field=models.IntegerField(default=0, null=True, verbose_name='Общая сумма всех товаров'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_discount_price',
            field=models.IntegerField(default=0, null=True, verbose_name='Общая сумма скидок'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_not_discount_price',
            field=models.IntegerField(default=0, null=True, verbose_name='Общая сумма цен без скидок'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_products',
            field=models.IntegerField(default=0, null=True, verbose_name='Количество товара'),
        ),
    ]
