# Generated by Django 4.0.5 on 2022-08-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cart_final_price_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='in_order',
            field=models.BooleanField(default=True, verbose_name='В заказе'),
        ),
    ]
