# Generated by Django 4.0.5 on 2022-08-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cartproduct_in_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='in_order',
            field=models.BooleanField(default=False, verbose_name='В заказе'),
        ),
    ]
