# Generated by Django 4.0.5 on 2022-07-31 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='favorite_products',
            field=models.ManyToManyField(blank=True, default=None, related_name='favorite_products', to=settings.AUTH_USER_MODEL, verbose_name='Добавить в избранное'),
        ),
        migrations.CreateModel(
            name='FavoriteUserProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Продукт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Favorite product',
                'verbose_name_plural': 'Favorite products',
            },
        ),
    ]
