# Generated by Django 4.0.5 on 2022-07-28 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_productsizeset_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_value', models.CharField(max_length=255, unique=True, verbose_name='Размер')),
                ('size_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='size_category', to='product.category')),
            ],
            options={
                'verbose_name': 'Product size',
                'verbose_name_plural': 'Product sizes',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_set_size',
        ),
        migrations.DeleteModel(
            name='ProductSizeSet',
        ),
        migrations.AddField(
            model_name='product',
            name='product_size',
            field=models.ManyToManyField(blank=True, related_name='product_sizes', to='product.productsize', verbose_name='Размер продукта'),
        ),
    ]
