# Generated by Django 4.0.5 on 2022-07-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, default='product/system_img/default.jpg', upload_to='product/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
