# Generated by Django 4.0.5 on 2022-07-15 17:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_productimage_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='full_price',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2147483647)], verbose_name='Полная стоимость'),
        ),
    ]
