# Generated by Django 4.0.5 on 2022-07-17 15:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='full_price',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2147483647)], verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_now',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена в данный момент'),
        ),
    ]
